### ISSUE TITLE
Template like variable substitution

### ISSUE THREAD

**Issue by icnocop** [iafan/Config-Neat#5]
Hi @iafan.

Thank you for Config::Neat.

I'd like to be able to substitute variables within a configuration file, making the inherited configuration file sort of like a template file.

For example:
template.config:
```
section1
{
    key1 %key1_value%
}
```

application.config:
```
# global variables to be substituted in template file
key1_value value1

# inherit template file
@inherit template.config#section1
```

So application.config is parsed and rendered as follows:
```
section1
{
    key1 value1
}
```

Variable substitution makes more sense when I have a configuration file with lots of sections, duplicate key values, or values within arrays that need to be replaced.

For example, I have a configuration file with hard-coded paths that are specific to machineA. Those paths are different on machineB.  I'd like to be able to re-use the same configuration file on both machines with minimal duplication.

Since root keys in a configuration file are valid, we may need another way to identify those variables.
We may also want to be able to override variables in inherited configuration files.

Should this feature actually be implemented in Config::Neat, or is there another pre-processor that you can recommend I use instead?

Or should this feature actually be implemented by the application consuming the configuration file ([serge](https://github.com/evernote/serge/))?

Thank you!

**Comment by iafan** [comment]
Good question. Indeed, this is something that is better be implemented on the consuming side (and this is exactly how Serge does it). Variable substitution is app-specific: you need to know how to expand those variables, and Config::Neat is a generic config parser that doesn't have that knowledge. If you want to make all your config parameters support such variables, what you could do is a higher-level config file class that extends or wraps Config::Neat::Inheritable, and once the config tree is parsed by underlying Config::Neat::Inheritable instance, it would go through all the values and substitute them with variables.

Speaking of your use case with hardcoded paths, the way it is done in Serge is by substituting environment variables that are set on a per-machine basis. Serge uses the `%ENV:XXXXXX%` notion for that. You can take the relevant Serge code as a source for inspiration: https://github.com/evernote/serge/blob/master/lib/Serge/Util.pm#L232-L379

**Comment by icnocop** [comment]
Thank you for the link to the source code and recommendation of using environment variables.

I also see sample usage in https://github.com/evernote/serge/blob/master/doc/sample.serge#L45-L55.

I was expecting to be able to use values specified in a file and not exclusively in environment variables.

I've created https://github.com/evernote/serge/issues/113.

Thank you.
