### ISSUE TITLE
plugin VCS doesn't work.

### ISSUE THREAD

**Issue by ilkarataev** [iafan/Config-Neat#7]
Hi i copied plugin to directory but i can't enable it.
![image](https://user-images.githubusercontent.com/27670867/66391196-ec22d880-e9e5-11e9-933c-db8477f4c5df.png)

**Comment by iafan** [comment]
I believe the issue was with an incorrect version number formatting in the package.json file. Can you try updating the extension files and seeing if it helps?

**Comment by ilkarataev** [comment]
Thank you it's working.
